#!/bin/sh

# 环境变量
export LANG='zh_CN.UTF-8'
export LC_ALL='zh_CN.UTF-8'
export GTK_IM_MODULE='fcitx'
export QT_IM_MODULE='fcitx'
export XMODIFIERS='@im=fcitx'

£ 剪贴板管理器
vncconfig -nowin &

# 虚拟声卡
/usr/local/bin/pulse-autostart.sh &

# Fcitx5输入法
fcitx5 &

# 启动微信
/usr/bin/wechat --no-sandbox &

exec /etc/X11/xinit/xinitrc