#!/bin/sh

# 环境变量
export LANG='zh_CN.UTF-8'
export LC_ALL='zh_CN.UTF-8'
export GTK_IM_MODULE='fcitx'
export QT_IM_MODULE='fcitx'
export XMODIFIERS='@im=fcitx'

# 剪贴板管理器
vncconfig -nowin &

exec /etc/X11/xinit/xinitrc